CREATE OR REPLACE TYPE NOTIFICATION AS OBJECT (
	image 					VARCHAR2(1000),
	text 						VARCHAR2(1024),
	url							VARCHAR2(100),
	timestamp 			VARCHAR2(100),
	seen						VARCHAR2(10)
);
/

CREATE OR REPLACE TYPE NOTIFICATION_ARRAY AS TABLE OF NOTIFICATION;
/