--------------------------------------------------------
--  File created - Saturday-July-16-2022   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table APPLIES
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."APPLIES" 
   (	"TUTOR_ID" NUMBER, 
	"POST_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table BATCHES
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."BATCHES" 
   (	"BATCH_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COURSE_ID" NUMBER, 
	"START_DATE" DATE, 
	"SEATS" NUMBER, 
	"STUDENTS" NUMBER DEFAULT 0, 
	"CLASS_DAYS" VARCHAR2(100 BYTE), 
	"CLASS_TIME" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COACHINGS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."COACHINGS" 
   (	"COACHING_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"IMAGE" VARCHAR2(100 BYTE) DEFAULT ON NULL 'coaching.png', 
	"NAME" VARCHAR2(100 BYTE), 
	"ADDRESS" VARCHAR2(1024 BYTE), 
	"PHONE_NUMBER" VARCHAR2(15 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COURSES
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."COURSES" 
   (	"COURSE_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"COACHING_ID" NUMBER, 
	"CLASS" VARCHAR2(100 BYTE), 
	"SUBJECT" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table ENROLLEDIN
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."ENROLLEDIN" 
   (	"STUDENT_ID" NUMBER, 
	"COURSE_ID" NUMBER, 
	"BATCH_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MEMBEROF
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."MEMBEROF" 
   (	"USER_ID" NUMBER, 
	"COACHING_ID" NUMBER, 
	"ROLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OFFERS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."OFFERS" 
   (	"STUDENT_ID" NUMBER, 
	"TUTOR_ID" NUMBER, 
	"TUTION_ID" NUMBER, 
	"STATUS" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table RATES
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."RATES" 
   (	"STUDENT_ID" NUMBER, 
	"TUTOR_ID" NUMBER, 
	"RATING" NUMBER
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table STUDENTS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."STUDENTS" 
   (	"STUDENT_ID" NUMBER, 
	"INSTITUTION" VARCHAR2(1024 BYTE), 
	"VERSION" VARCHAR2(1024 BYTE), 
	"CLASS" VARCHAR2(1024 BYTE), 
	"ADDRESS" VARCHAR2(1024 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TUTIONS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."TUTIONS" 
   (	"TUTION_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"SUBJECTS" VARCHAR2(1024 BYTE), 
	"SALARY" NUMBER, 
	"DAYS_PER_WEEK" NUMBER, 
	"ROLE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TUTION_POSTS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."TUTION_POSTS" 
   (	"POST_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"STUDENT_ID" NUMBER, 
	"TUTION_ID" NUMBER, 
	"TIMESTAMP" TIMESTAMP (6) DEFAULT systimestamp, 
	"DESIRED_TUTOR_GENDER" VARCHAR2(10 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TUTORS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."TUTORS" 
   (	"TUTOR_ID" NUMBER, 
	"EXPERTISE" VARCHAR2(1024 BYTE), 
	"AVAILABILITY" VARCHAR2(100 BYTE), 
	"YEARS_OF_EXPERIENCE" NUMBER, 
	"PREFFERED_SALARY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table USERS
--------------------------------------------------------

  CREATE TABLE "C##HIDDENBRAIN"."USERS" 
   (	"USER_ID" NUMBER GENERATED ALWAYS AS IDENTITY MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE , 
	"NAME" VARCHAR2(100 BYTE), 
	"IMAGE" VARCHAR2(1000 BYTE) DEFAULT ON NULL 'sample.jpg', 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PASS" VARCHAR2(1024 BYTE), 
	"ROLE" VARCHAR2(1024 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"PHONE_NUMBER" VARCHAR2(15 BYTE), 
	"DATE_OF_BIRTH" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into C##HIDDENBRAIN.APPLIES
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.APPLIES (TUTOR_ID,POST_ID) values (4,1);
Insert into C##HIDDENBRAIN.APPLIES (TUTOR_ID,POST_ID) values (5,1);
Insert into C##HIDDENBRAIN.APPLIES (TUTOR_ID,POST_ID) values (6,1);
Insert into C##HIDDENBRAIN.APPLIES (TUTOR_ID,POST_ID) values (7,2);
REM INSERTING into C##HIDDENBRAIN.BATCHES
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.BATCHES (BATCH_ID,COURSE_ID,START_DATE,SEATS,STUDENTS,CLASS_DAYS,CLASS_TIME) values (1,1,to_date('20-AUG-19','DD-MON-RR'),30,0,'SUN-TUE-THU','1.00PM-2.00PM');
Insert into C##HIDDENBRAIN.BATCHES (BATCH_ID,COURSE_ID,START_DATE,SEATS,STUDENTS,CLASS_DAYS,CLASS_TIME) values (2,2,to_date('23-JUL-22','DD-MON-RR'),25,0,'Sun,Tue,Thu','12:00 PM-1:00 PM');
Insert into C##HIDDENBRAIN.BATCHES (BATCH_ID,COURSE_ID,START_DATE,SEATS,STUDENTS,CLASS_DAYS,CLASS_TIME) values (3,3,to_date('10-OCT-22','DD-MON-RR'),30,0,'THU-FRI-SAT','3.00PM-4.30PM');
Insert into C##HIDDENBRAIN.BATCHES (BATCH_ID,COURSE_ID,START_DATE,SEATS,STUDENTS,CLASS_DAYS,CLASS_TIME) values (4,4,to_date('10-AUG-22','DD-MON-RR'),30,0,'SAT-MON-WED','8.00AM-10.00AM');
REM INSERTING into C##HIDDENBRAIN.COACHINGS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (1,'coaching1.jpg','Break The Fear','Ahmed Mansion, Monoharpur, Cumilla','01851953433');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (2,'coaching2.jpg','Alphateach','69/C, Monipuri Para, Tejgaon','01711130955');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (3,'coaching3.jpg','Brilliant Minds','Indira Road, Farmgate, Dhaka','01978290355');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (4,'coaching4.jpg','Bold Academy','House #285/3, Road #15 (old), Dhanmondi','01755577908');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (5,'coaching5.jpg','Educatree','20, Central road, Dhanmondi Residential Aria','01851953433');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (6,'coaching6.jpg','Education Hub','Samsur rahman road, Khulna, Khulna','01655567659');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (7,'coaching7.jpg','Instant Academy','Bakshibazar, Dhaka medical college and hospital, Dhaka','01755533650');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (8,'coaching8.jpg','Study Point','U-49, Noorjahan road, Mohammadpur, Dhaka','01555556769');
Insert into C##HIDDENBRAIN.COACHINGS (COACHING_ID,IMAGE,NAME,ADDRESS,PHONE_NUMBER) values (9,'coaching9.jpg','Coachify','145/28, Airport road super market (1st floor), Tejgaon, Dhaka','01313854014');
REM INSERTING into C##HIDDENBRAIN.COURSES
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (1,1,'Ten','Physics');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (2,1,'Five','Bangla');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (3,1,'Eight','Math');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (4,1,'Twelve','Physics');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (5,2,'Ten','Physics');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (6,2,'Five','Bangla');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (7,2,'Eight','Math');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (8,3,'Five','English');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (9,3,'Four','Bangla');
Insert into C##HIDDENBRAIN.COURSES (COURSE_ID,COACHING_ID,CLASS,SUBJECT) values (10,3,'Eleven','Chemistry');
REM INSERTING into C##HIDDENBRAIN.ENROLLEDIN
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.ENROLLEDIN (STUDENT_ID,COURSE_ID,BATCH_ID) values (1,1,1);
Insert into C##HIDDENBRAIN.ENROLLEDIN (STUDENT_ID,COURSE_ID,BATCH_ID) values (1,2,2);
Insert into C##HIDDENBRAIN.ENROLLEDIN (STUDENT_ID,COURSE_ID,BATCH_ID) values (1,3,3);
REM INSERTING into C##HIDDENBRAIN.MEMBEROF
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (1,1,'MEMBER');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (1,2,'MEMBER');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (1,3,'MEMBER');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (2,2,'MEMBER');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (2,4,'MEMBER');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (3,5,'MEMBER');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (4,1,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (4,2,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (5,3,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (5,4,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (6,5,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (6,6,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (7,7,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (8,8,'ADMIN');
Insert into C##HIDDENBRAIN.MEMBEROF (USER_ID,COACHING_ID,TYPE) values (9,9,'ADMIN');
REM INSERTING into C##HIDDENBRAIN.OFFERS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.OFFERS (STUDENT_ID,TUTOR_ID,TUTION_ID,STATUS) values (1,4,8,'ACCEPTED');
Insert into C##HIDDENBRAIN.OFFERS (STUDENT_ID,TUTOR_ID,TUTION_ID,STATUS) values (1,5,9,'ACCEPTED');
Insert into C##HIDDENBRAIN.OFFERS (STUDENT_ID,TUTOR_ID,TUTION_ID,STATUS) values (1,6,10,'ACCEPTED');
Insert into C##HIDDENBRAIN.OFFERS (STUDENT_ID,TUTOR_ID,TUTION_ID,STATUS) values (2,4,11,'PENDING');
Insert into C##HIDDENBRAIN.OFFERS (STUDENT_ID,TUTOR_ID,TUTION_ID,STATUS) values (2,5,12,'PENDING');
Insert into C##HIDDENBRAIN.OFFERS (STUDENT_ID,TUTOR_ID,TUTION_ID,STATUS) values (2,6,13,'PENDING');
REM INSERTING into C##HIDDENBRAIN.RATES
SET DEFINE OFF;
REM INSERTING into C##HIDDENBRAIN.STUDENTS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.STUDENTS (STUDENT_ID,INSTITUTION,VERSION,CLASS,ADDRESS) values (1,'NDC','Bangla','HSC - 2nd year','38/1, Indira Road, Farmgate, Dhaka');
Insert into C##HIDDENBRAIN.STUDENTS (STUDENT_ID,INSTITUTION,VERSION,CLASS,ADDRESS) values (2,'YWCA','Bangla','8','38/1, Indira road, Dhaka');
Insert into C##HIDDENBRAIN.STUDENTS (STUDENT_ID,INSTITUTION,VERSION,CLASS,ADDRESS) values (3,'NDC','Bangla','12','Banasree, Dhaka');
REM INSERTING into C##HIDDENBRAIN.TUTIONS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (1,'Math',10000,3,'Offline');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (2,'Physics',5000,3,'Offline');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (3,'Math',8000,3,'Offline');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (4,'Math, Physics, Chemistry',10000,4,'Online');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (5,'Bangla, English',5000,4,'Offline');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (6,'Math, Physics, Chemistry',10000,4,'Online');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (7,'C++',5000,3,'Online');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (8,'Math, Physics, Chemistry',10000,3,'Online');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (9,'English',8000,2,'Offline');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (10,'Bangla',5000,3,'Online');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (11,'Math',10000,3,'Offline');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (12,'Math',12000,7,'Online');
Insert into C##HIDDENBRAIN.TUTIONS (TUTION_ID,SUBJECTS,SALARY,DAYS_PER_WEEK,TYPE) values (13,'English, Bangla',5000,5,'Offline');
REM INSERTING into C##HIDDENBRAIN.TUTION_POSTS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (1,1,1,to_timestamp('16-JUL-22 01.12.28.723000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Male');
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (2,1,2,to_timestamp('16-JUL-22 01.12.28.731000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Female');
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (3,1,3,to_timestamp('16-JUL-22 01.12.28.749000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Male');
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (4,1,4,to_timestamp('16-JUL-22 01.12.28.763000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Male');
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (5,2,5,to_timestamp('16-JUL-22 01.12.28.779000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Male');
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (6,2,6,to_timestamp('16-JUL-22 01.12.28.791000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Male');
Insert into C##HIDDENBRAIN.TUTION_POSTS (POST_ID,STUDENT_ID,TUTION_ID,TIMESTAMP,DESIRED_TUTOR_GENDER) values (7,2,7,to_timestamp('16-JUL-22 01.12.28.805000000 PM','DD-MON-RR HH.MI.SSXFF AM'),'Female');
REM INSERTING into C##HIDDENBRAIN.TUTORS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (4,'Math, Physics, Chemistry','Available',4,10000);
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (5,'Math, ICT','Available',2,8000);
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (6,'Math','Available',3,10000);
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (7,'Physics','Available',3,10000);
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (8,'Math, Physics, Chemistry','Unavailable',3,10000);
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (9,'Math','Unavailable',3,10000);
Insert into C##HIDDENBRAIN.TUTORS (TUTOR_ID,EXPERTISE,AVAILABILITY,YEARS_OF_EXPERIENCE,PREFFERED_SALARY) values (10,'English','Available',3,10000);
REM INSERTING into C##HIDDENBRAIN.USERS
SET DEFINE OFF;
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (1,'Mahir Labib Dihan','male_student.jpg','mahirlabibdihan@gmail.com','$2a$10$8GBsWOPaNtD5gUZu1bNB7uCh0mk3Y6NY25SnGTr1mbuWwKsFPYY5G','STUDENT','Male','01851953433',to_date('19-AUG-01','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (2,'Noushin Tarannum Subha','female_student.jpg','noushintarannum@gmail.com','$2a$10$t7tfxUp7R/loxmxKcuAbY.sObMjcHiwrps/mTpq0/1jJqlfj9BCl2','STUDENT','Female','01851953433',to_date('01-OCT-07','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (3,'Muntasir Mamun Nahid','male_student.jpg','nahidtakla@gmail.com','$2a$10$cNR392ChvTW9rJ4BUY8fDep68xgk7MlJ0pgB.HIAkA/E69HKSSeM2','STUDENT','Male','01684828706',to_date('27-AUG-01','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (4,'Mahir Tazwar Ohi','tutor1.jpg','mahirtazwarohi@gmail.com','$2a$10$8GBsWOPaNtD5gUZu1bNB7uCh0mk3Y6NY25SnGTr1mbuWwKsFPYY5G','TUTOR','Male','01767493500',to_date('03-DEC-00','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (5,'Md Sharif Uddin','tutor2.jpg','sharif@gmail.com','$2a$10$8GBsWOPaNtD5gUZu1bNB7uCh0mk3Y6NY25SnGTr1mbuWwKsFPYY5G','TUTOR','Male','01867549950',to_date('03-MAR-00','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (6,'Tareq Ahmed','tutor3.jpg','1905071@gmail.com','$2a$10$GgiK3IOV9GluNyOnl.P0xO/jnfIudswCvwdKLFm0SKd39sHi4Misq','TUTOR','Male','01478066006',to_date('01-JAN-00','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (7,'Souvik Ghosh','tutor4.jpg','1905073@gmail.com','$2a$10$GgiK3IOV9GluNyOnl.P0xO/jnfIudswCvwdKLFm0SKd39sHi4Misq','TUTOR','Male','01911714385',to_date('01-JAN-00','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (8,'Sadat Hossain','tutor5.jpg','1905001@gmail.com','$2a$10$GgiK3IOV9GluNyOnl.P0xO/jnfIudswCvwdKLFm0SKd39sHi4Misq','TUTOR','Male','01891578643',to_date('01-JAN-00','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (9,'Anindya Hoque','tutor6.jpg','1905070@gmail.com','$2a$10$GgiK3IOV9GluNyOnl.P0xO/jnfIudswCvwdKLFm0SKd39sHi4Misq','TUTOR','Male','01881536649',to_date('01-JAN-00','DD-MON-RR'));
Insert into C##HIDDENBRAIN.USERS (USER_ID,NAME,IMAGE,EMAIL,PASS,TYPE,GENDER,PHONE_NUMBER,DATE_OF_BIRTH) values (10,'Syeda Rifah Tasfia','tutor7.jpg','1905019@gmail.com','$2a$10$GgiK3IOV9GluNyOnl.P0xO/jnfIudswCvwdKLFm0SKd39sHi4Misq','TUTOR','Female','01891556749',to_date('01-JAN-00','DD-MON-RR'));
