const router = require("express").Router();
const authMiddleware = require("../service/tokenValidationService");
const CoachingController = require("../controller/coachingController");
const coachingController = new CoachingController();

router.use(authMiddleware);
router.route("/update_info").post(coachingController.updateInfo);
router.post("/upload", coachingController.setProfilePicture);
router.route("/create").post(coachingController.create);
router.route("/get_info").post(coachingController.getInfo);
router.route("/list").get(coachingController.getList);
router.route("/join_list").get(coachingController.getJoinList);
router.route("/my_list").get(coachingController.getMyList);
router.route("/notices").get(coachingController.getMyNotices);
router.route("/notices").post(coachingController.postNotice);
router.route("/course_list").post(coachingController.getCourseList);
router.route("/join").post(coachingController.joinCoaching);
router.route("/join/approve").post(coachingController.approveJoinRequest);
router.route("/join/decline").post(coachingController.declineJoinRequest);
router.route("/join/cancel").post(coachingController.cancelJoinRequest);
module.exports = router;
