CREATE OR REPLACE TRIGGER CHECK_EMAIL
	BEFORE INSERT
	ON USERS
	FOR EACH ROW
DECLARE	
	user_row Users%ROWTYPE;
BEGIN
	IF IS_EMAIL_TAKEN(:NEW.email) = 'YES' THEN
		RAISE_APPLICATION_ERROR(-20999, 'Email is already taken');
	END IF;
END;
/
