CREATE OR REPLACE TRIGGER CHECK_BATCH_LIMIT
	BEFORE INSERT
	ON EnrolledIn
	FOR EACH ROW
DECLARE	
	student_count NUMBER;
BEGIN
	IF GET_BATCH_STUDENT_COUNT(:NEW.batch_id) = GET_SEAT_COUNT(:NEW.batch_id) THEN
		RAISE_APPLICATION_ERROR(-20999, 'Batch is full');
	END IF;
END;
/
